server:
  port: 8088
spring:
  application:
    name: graduation-project
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/bicycle?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.graduation.bean,com.graduation.dto
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: del
  configuration:
    map-underscore-to-camel-case: true
api:
  swagger:
    title: API接口
    description: 单车租赁接口文档
    version: 1.0.0
    contact:
      name: yue
      email: yue@123.com
    base-package: com.graduation.controller.rest
knife4j:
  enable: true
  basic:
    enable: true
    username: swagger
    password: swagger
logging:
  level:
    com.wz: debug
    com.graduation: debug
  file:
    name: ${spring.application.name}
